### ISSUE TITLE
Contact form, 404 page, and other vaguely related things

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#31]
404 page (when they access a page that doesn't actually exist):

![image](https://user-images.githubusercontent.com/29292463/29997168-7e904c6a-8fda-11e7-9190-297d4ab62e50.png)

I'm fixing up the contact page now so that when you click on scenario specific links (ex. website error), specialized stuff occurs. Kinda hard to test until we get hosting figured out tho.

**Comment by mcdoash** [comment]
I'm just going to write a to-do list of those vaguely related things here:

# To-Do
## Must Finish
- [x] Sitemap
- [x] Fix meta data
- [x] Submit to google
- [x] Validation
- [x] Optimization

## Would be Nice
- [ ] Accessibility
- [ ] Rest of Javascript-disabled

**Comment by Amyffz** [comment]
woah the error sign is really nice

**Comment by mcdoash** [comment]
@Amyffz thank you!!!

**Comment by mcdoash** [comment]
Took me 10 hours but the contact form is finally done!!!!  🎉 Just have to wait for hosting to implement and test it.

**Comment by mcdoash** [comment]
Finally got the contact form to work!!!

**Comment by mcdoash** [comment]
We're officially ranked in Google, which was the unsaid end goal of this issue, so I think it's alright to close.
