### ISSUE TITLE
Ultimate Pre-Launch Checklist!

### ISSUE THREAD

**Issue by mcdoash** [CentralProgramming/CentralProgramming.github.io#34]
*Please* if you can, complete something in this list. Like maybe your paragraph in the Team section on the main page (**HINT**)? Also feel free to add anything to this list.

## Website
- [ ] Content #12 (see checklist there)
     - [x] **TEAM SECTION** @Fay-Z @Amyffz @AngelaZ0 
     - [x] Finalize
- [x] Hosting & Domain #19 
     - [x] Tons of PHP work to be done here
- [x] "Admin" junk #31 
- [x] SQL weekly problems

## Promotional
- [x] Finish poster #33  @Amyffz 
- [x] Write announcement

## Meetings
- [x] Decide on first meeting (discussion started at #33 )
- [x] First meeting itinerary/"script"

**Comment by Amyffz** [comment]
ashley, why did you use they instead of her?

**Comment by Amyffz** [comment]
something like this for mine:
To Amy, programming is all about creating something out of nothing. With a few lines of code and the desire to discover and explore, she finds herself solving questions that are otherwise impossible. Amy loves to challenge herself with computer contests that push her thinking to the next level.

**Comment by mcdoash** [comment]
Oh whoops, I think when I first did mine I was just going to use they for everyone (?) but when I edited the others I used she. I'll fix mine now. 
Thanks, that's awesome!!!

**Comment by mcdoash** [comment]
I tried rewriting mine because I really didn't like it, but I'm just not good at writing these kinds of things. Does this sound awkward? @Amyffz 
"Ashley’s favourite and least favourite part of programming is spending hours trying to figure out why it isn’t working (only for it to be a typo). The satisfaction of finally solving a difficult problem is one of the reason she enjoys contests so much. Ashley’s main interest is in software and game design."

**Comment by mcdoash** [comment]
Hey, I forgot about this issue. I think with the recent leaderboard/past problems update it should be good to resolve, and officially mark this as version 1.0!

**Comment by mcdoash** [comment]
<img width="1438" alt="central_programming_club_and_calendar" src="https://user-images.githubusercontent.com/29292463/33811593-654d5ad4-dde3-11e7-8478-104334acdfa0.png">
I need to put this here for reasons.
